services:
  - type: web
    name: kanban-task-uploader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/main.py --server.port=8080 --server.enableCORS false
